# Generated by Django 3.2 on 2021-04-27 04:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ssn', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 14', regex='^[0-9]{14}$')])),
            ],
        ),
        migrations.CreateModel(
            name='CoursesGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level', models.CharField(choices=[('اول ابتدائي', 'اول ابتدائي'), ('ثاني ابتدائي', 'ثاني ابتدائي'), ('ثالث ابتدائي', 'ثالث ابتدائي'), ('رابع ابتدائي', 'رابع ابتدائي'), ('خامس ابتدائي', 'خامس ابتدائي'), ('سادس ابتدائي', 'سادس ابتدائي'), ('اول اعدادي', 'اول اعدادي'), ('ثاني اعدادي', 'ثاني اعدادي'), ('ثالث اعدادي', 'ثالث اعدادي'), ('اول ثانوي', 'اول ثانوي'), ('ثاني ثانوي', 'ثاني ثانوي'), ('ثالث ثانوي', 'ثالث ثانوي'), ('اخري', 'اخري')], max_length=55)),
                ('session_num', models.IntegerField()),
                ('start_date', models.DateField()),
                ('next_session_date', models.DateField()),
                ('next_session_time', models.TimeField()),
                ('schedule', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('binding', 'binding'), ('active', 'active')], max_length=20)),
                ('image', models.ImageField(blank=True, default='moasasa/reservation/images/default.jpg', null=True, upload_to='moasasa/reservation/images')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level', models.CharField(choices=[('اول ابتدائي', 'اول ابتدائي'), ('ثاني ابتدائي', 'ثاني ابتدائي'), ('ثالث ابتدائي', 'ثالث ابتدائي'), ('رابع ابتدائي', 'رابع ابتدائي'), ('خامس ابتدائي', 'خامس ابتدائي'), ('سادس ابتدائي', 'سادس ابتدائي'), ('اول اعدادي', 'اول اعدادي'), ('ثاني اعدادي', 'ثاني اعدادي'), ('ثالث اعدادي', 'ثالث اعدادي'), ('اول ثانوي', 'اول ثانوي'), ('ثاني ثانوي', 'ثاني ثانوي'), ('ثالث ثانوي', 'ثالث ثانوي'), ('اخري', 'اخري')], max_length=20)),
                ('phone', models.CharField(max_length=11)),
                ('image', models.ImageField(blank=True, default='moasasa/students/images/default.jpg', null=True, upload_to='moasasa/students/images')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('phone', models.CharField(max_length=11)),
                ('image', models.ImageField(blank=True, default='moasasa/teachers/images/default.jpg', null=True, upload_to='moasasa/teachers/images')),
            ],
        ),
    ]
