# Generated by Django 3.2 on 2021-04-23 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moasasa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, default='moasasa/students/images/default.jpg', null=True, upload_to='moasasa/students/images'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, default='moasasa/teachers/images/default.jpg', null=True, upload_to='moasasa/teachers/images'),
        ),
    ]
