# Generated by Django 3.2 on 2021-04-11 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moasasa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesgroup',
            name='image',
        ),
    ]
