# Generated by Django 3.2 on 2021-04-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moasasa', '0002_remove_coursesgroup_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('اول ابتدائي', 'اول ابتدائي'), ('ثاني ابتدائي', 'ثاني ابتدائي'), ('ثالث ابتدائي', 'ثالث ابتدائي'), ('رابع ابتدائي', 'رابع ابتدائي'), ('خامس ابتدائي', 'خامس ابتدائي'), ('سادس ابتدائي', 'سادس ابتدائي'), ('اول اعدادي', 'اول اعدادي'), ('ثاني اعدادي', 'ثاني اعدادي'), ('ثالث اعدادي', 'ثالث اعدادي'), ('اول ثانوي', 'اول ثانوي'), ('ثانوي ثانوي', 'ثانوي ثانوي'), ('ثالث ثانوي', 'ثالث ثانوي'), ('اخري', 'اخري')], max_length=20),
        ),
    ]
